name: Scrape PHIVOLCS Earthquake Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  scrape:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
run:pip install -r requirement.txt


      - name: Run scraper
        run: python scrape_phivolcs.py

      - name: Commit updated CSV
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add phivolcs_earthquakes.csv
          git commit -m "Update earthquake data"
          git push
